version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql       
    environment:
      MYSQL_DATABASE: fitopsdb   
      MYSQL_USER: fitops         
      MYSQL_PASSWORD: fitops123  
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  my-app:
    build: .
    container_name: my-running-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql             
    restart: always

volumes:
  mysql_data:

