apiVersion: v1
kind: ConfigMap
metadata:
  name: fitops-config
  namespace: fitops
data:
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: fitopsdb
  OLLAMA_URL: http://ollama-service:11434
  SERVER_FORWARD_HEADERS_STRATEGY: native
