apiVersion: v1
kind: Secret
metadata:
  name: fitops-secret
  namespace: fitops
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD_PLACEHOLDER
  MYSQL_USER: MYSQL_USER_PLACEHOLDER
  MYSQL_PASSWORD: MYSQL_PASSWORD_PLACEHOLDER
