kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
     name: fitops-hpa
spec:
     scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: fitops-deployment
     minReplicas: 2
     maxReplicas: 5
     metrics:
     - type: Resource
       resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 50
