name: Code Quality

on:
   workflow_call: 

jobs:
    validate:
          runs-on: ubuntu-latest
          strategy:
                fail-fast: false
                matrix:
                     python-version: ['3.11']

          steps:
             - name: checkout code
               uses: actions/checkout@v4

             - name: setup python ${{ matrix.python-version }}
               uses: actions/setup-python@v5
               with:
                  python-version: ${{ matrix.python-version }}

             - name: install dependencies
               run: pip install -r requirements-DevSecOps.txt

             - name: Setup Log Catcher
               run: touch code_quality_errors.log

             - name: run linter
               run: |
                  echo "=== Flake8 Linting Violations⚠️ ===" >> code_quality_errors.log
                  flake8 >> code_quality_errors.log 2>&1 || true

             - name: SAST
               run: |
                  echo "=== Bandit SAST Violations⚠️ ===" >> code_quality_errors.log
                  bandit -r app.py -s B104 >> code_quality_errors.log 2>&1 || true

             - name: Upload Quality Scan Log
               uses: actions/upload-artifact@v4
               with:
                 name: code-quality-log
                 path: code_quality_errors.log
