name: Dependency Scan
on:
   workflow_call:

jobs:
    depedency-check:
               runs-on: ubuntu-latest
               steps: 
                   - name: Code Checkout
                     uses: actions/checkout@v4

                   - name: setup python-version 3.12
                     uses: actions/setup-python@v5
                     with:
                         python-version: "3.12"

                   - name: Install Pip Audit
                     run: pip install pip-audit

                   - name: Setup Log Catcher
                     run: touch dependency_errors.log
                  
                   - name: Audit Dependencies
                     run: |
                        echo "=== Pip Audit Dependency Vulnerabilities ===" >> dependency_errors.log
                        pip-audit -r ./app/requirements.txt -r requirements-DevSecOps.txt --ignore-vuln CVE-2026-4539 >> dependency_errors.log 2>&1 || true

                   - name: Upload Dependency Scan Log
                     uses: actions/upload-artifact@v4
                     with:
                       name: dependency-scan-log
                       path: dependency_errors.log

