name: Deploy to Server

on:
   workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha }}

        steps:
           - name: Checkout Code
             uses: actions/checkout@v4

           - name: Copy the Setup File in Master Node
             uses: appleboy/scp-action@v1
             with:
                 host: ${{ secrets.MASTER_SSH_HOST }}
                 username: ${{ secrets.EC2_SSH_USER }}
                 key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                 source: setup.sh
                 target: "~/"


           - name: SSH to k8s Master node & Execute the file
             id: master_init
             uses: appleboy/ssh-action@v1.0.3
             with:
                 host: ${{ secrets.MASTER_SSH_HOST }}
                 username: ${{ secrets.EC2_SSH_USER }}
                 key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                 capture_stdout: true
                 script: |
                         chmod +x ~/setup.sh
                          ~/setup.sh 
                     
                     
           - name: Copy the Setup File in Worker Node
             uses: appleboy/scp-action@v1
             with:
                 host: ${{ secrets.WORKER_SSH_HOST }}
                 username: ${{ secrets.EC2_SSH_USER }}
                 key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                 source: setupW.sh
                 target: "~/"

           - name: Download join file from Master
             run: |
                  echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > master_key.pem
                  chmod 600 master_key.pem
                  scp -i master_key.pem -o StrictHostKeyChecking=no \
                  ${{ secrets.EC2_SSH_USER }}@${{ secrets.MASTER_SSH_HOST }}:~/join-command.sh ./join-command.sh


           - name: Upload join file to Worker
             uses: appleboy/scp-action@v0.1.7
             with:
                  host: ${{ secrets.WORKER_SSH_HOST }}
                  username: ${{ secrets.EC2_SSH_USER }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  source: "join-command.sh"
                  target: "~/"
           
           - name: SSH to k8s Worker node & Execute the file
             uses: appleboy/ssh-action@v1.0.3
             with:
                 host: ${{ secrets.WORKER_SSH_HOST }}
                 username: ${{ secrets.EC2_SSH_USER }}
                 key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                 envs: MASTER_OUTPUT
                 script: |
                       chmod +x ~/setupW.sh
                        ~/setupW.sh
                        if [ ! -f /etc/kubernetes/kubelet.conf ]; then
                             echo "Executing join command from file..."
                             sudo ~/join-command.sh
                        else
                             echo "Already joined."
                         fi
                     

           - name: Copy K8s manifests to Master
             uses: appleboy/scp-action@v1
             with:
                 host: ${{ secrets.MASTER_SSH_HOST }}
                 username: ${{ secrets.EC2_SSH_USER }}
                 key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                 source: "manifests/"
                 target: "~/"

           - name: Deploy to Kubernetes
             uses: appleboy/ssh-action@v1.0.3
             with:
                 host: ${{ secrets.MASTER_SSH_HOST }}
                 username: ${{ secrets.EC2_SSH_USER }}
                 key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                 script: |
                     # Creating secret
                     kubectl delete secret app-secret --ignore-not-found
                     kubectl create secret generic app-secret \
                     --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}"
                     # Updating the image tags in the manifest file dynamically
                     sed -i "s|DOCKERHUB_USER|${{ vars.DOCKERHUB_USER }}|g" ~/manifests/deployment.yml
                     sed -i "s|DOCKER_TAG|${{ github.sha }}|g" ~/manifests/deployment.yml 
                     cat ~/manifests/deployment.yml | grep image
                     # Applying the manifests
                     kubectl apply -f ~/manifests/
                     # checking rollout status
                     kubectl rollout status deployment/fitops-deployment
