name: Deploy to Server

on:
   workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha }}

        steps:
           - name: Checkout Code
             uses: actions/checkout@v4

           - name: Copy the Setup File in Master Node
             uses: appleboy/scp-action@v1
             with:
                 host: ${{ secrets.MASTER_SSH_HOST }}
                 username: ${{ secrets.MASTER_SSH_USER }}
                 key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
                 source: setup.sh
                 target: "~/"


           - name: SSH to k8s Master node & Execute the file
             id: master_init
             uses: appleboy/ssh-action@v1.0.3
             with:
                 host: ${{ secrets.MASTER_SSH_HOST }}
                 username: ${{ secrets.MASTER_SSH_USER }}
                 key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
                 capture_stdout: true
                 script: |
                         chmod +x ~/setup.sh
                          ~/setup.sh 
                     
                     
           - name: Copy the Setup File in Worker Node
             uses: appleboy/scp-action@v1
             with:
                 host: ${{ secrets.WORKER_SSH_HOST }}
                 username: ${{ secrets.WORKER_SSH_USER }}
                 key: ${{ secrets.WORKER_SSH_PRIVATE_KEY }}
                 source: setupW.sh
                 target: "~/"


           - name: SSH to k8s Worker node & Execute the file
             uses: appleboy/ssh-action@v1.0.3
             with:
                 host: ${{ secrets.WORKER_SSH_HOST }}
                 username: ${{ secrets.WORKER_SSH_USER }}
                 key: ${{ secrets.WORKER_SSH_PRIVATE_KEY }}
                 script: |
                       chmod +x ~/setupW.sh
                        ~/setupW.sh
                        sudo ${{ steps.master_init.outputs.stdout }}
                     


           - name: SSH to Master Node & run the app
             uses: appleboy/ssh-action@v1.0.3
             with:
                 host: ${{ secrets.MASTER_SSH_HOST }}
                 username: ${{ secrets.MASTER_SSH_USER }}
                 key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
                 script: |
                     echo "Running the app"
                     export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                     export DOCKER_TAG=${{ github.sha }}
                     echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin
                     cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always
