name: DevSecOps End-to-End Pipeline Deployment

on:
    push:
       branches: [main]
       paths:
          - '.'
          - 'manifests/*'
          - '.github/workflows/*'
    workflow_dispatch:

permissions:
    contents: write

jobs:

       dependencies-installation:
           runs-on: ubuntu-latest

           steps:
             - name: Checkout code
               uses: actions/checkout@v4

             - name: Set up Python
               uses: actions/setup-python@v5
               with:
                  python-version: '3.11'

             - name: Install dependencies
               run: |
                   pip install -r requirements-DevSecOps.txt

       code-quality:
            needs: dependencies-installation
            uses: ./.github/workflows/code-quality.yml

       secrets-scan:
            needs: dependencies-installation
            uses: ./.github/workflows/secrets-scan.yml
            secrets: inherit

       dependency-scan:
            needs: dependencies-installation
            uses: ./.github/workflows/dependency-scan.yml

       docker-scan:
            needs: dependencies-installation
            uses: ./.github/workflows/docker-lint.yml


       CI:
            needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
            uses: ./.github/workflows/ci-job.yml
            secrets: inherit
