name: DevSecOps End-to-End Pipeline

on:
    push:
       branches: [main]
       paths:
          - 'app.py'
          - 'fitops.py'
          - 'models.py'
          - 'templates/*'
          - 'static/*'
          - 'manifests/*'
          - '.github/workflows/*'
    workflow_dispatch:

jobs:

       dependencies-installation:
           runs-on: ubuntu-latest

           steps:
             - name: Checkout code
               uses: actions/checkout@v4

             - name: Set up Python
               uses: actions/setup-python@v5
               with:
                  python-version: '3.11'

             - name: Install dependencies
               run: |
                   pip install -r requirements.txt -r requirements-DevSecOps.txt

       code-quality:
            uses: ./.github/workflows/code-quality.yml

       secrets-scan:
            uses: ./.github/workflows/secrets-scan.yml
            secrets: inherit

       dependency-scan:
            uses: ./.github/workflows/dependency-scan.yml

       docker-scan:
            uses: ./.github/workflows/docker-lint.yml


       CI:
            needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
            uses: ./.github/workflows/ci-job.yml
            secrets: inherit
