name: Secrets Scan

on:
    workflow_call:

jobs:
    secrets-scan:
            runs-on: ubuntu-latest
            
            steps:
               - name: Checkout Code
                 uses: actions/checkout@v4
                 with: 
                    fetch-depth: 0

               - name: Run Gitleaks Scanner
                 uses: gitleaks/gitleaks-action@v2
                 continue-on-error: true
                 env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                   GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
                   GITLEAKS_ARGS: "--report-path=secret_errors.log --report-format=text"

               - name: Ensure Log File Exists
                 run: touch secret_errors.log

               - name: Upload Secrets Scan Log
                 uses: actions/upload-artifact@v4
                 with:
                   name: secret-scan-log
                   path: secret_errors.log
